### PR TITLE
Relocation error

### PR DESCRIPTION
**Pull request by snoweye**
- I think for linux is working without `getipaddr()`
- I test on Solaris 10, but failed with a relocation error for `socket()` symbol not found ...
- I have tested as much as I can on Solaris 10, but I have run out of idea why it does not work.
- I will try if Solaris 11 has the same problems.

### CODE REVIEW

**Comment by wrathematics** [comment]
Dude, I don't care if this doesn't work on solaris. But I want everything to be in-process only.

**Comment by snoweye** [comment]
- It is in-process only. The R function is for validation.
- You can use "-DNO_IFADDRS" and "-DHAS_IFADDRS" to test in Linux. Both should give you the same ip.
- Because `getipaddr()` is not portable!

**Comment by snoweye** [comment]
- solaris checked without `ifaddr.h`, # of interfaces problem solved
- ubuntu checked for both with and without `ifaddr.h`
- windows installed as no changes
- mac unknown

**Comment by wrathematics** [comment]
I've tested `ip_internal_nix()` on my mac test machine and it works.

**Pull request merged**
